spring:
  config:
    activate:
      on-profile: prod,dev

  datasource:
    url: jdbc:mysql://${properties.data.mysql.host}:${properties.data.mysql.port}/${properties.data.mysql.database}?rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${properties.data.mysql.username}
    password: ${properties.data.mysql.password}
    hikari:
      max-lifetime: 600000
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        default_batch_fetch_size: 1000
        format_sql: true

  data:
    redis:
      host: ${properties.data.redis.host}
      port: ${properties.data.redis.port}
      password: ${properties.data.redis.password}